// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"
#include "ui_Screen9.h"
#include "ui_Screen10.h"


///////////////////// VARIABLES ////////////////////





//////////wifi
extern bool WIFI_SCAN_FLAG; // Scan flag, 1 for starting scan
extern bool WIFI_STA_FLAG; // Connection flag, 1 for starting connection to AP
extern bool WIFI_AP_FLAG; // AP flag, 1 for opening AP
extern bool WIFI_DIS_PWD; // Flag for showing password, 1 for visible password
extern bool WIFI_AP_PWD; // Flag for AP password visibility, 1 for visible password
extern int8_t WIFI_CONNECTION; // Flag for successful WIFI connection, stores position of connection in list
extern int wifi_index; // Index of selected WIFI
extern uint8_t *wifi_pwd; // Pointer to WIFI password
extern bool WIFI_CONNECTION_DONE;

extern lv_obj_t *ui_WIFI_SCAN_List; // WIFI scan list object
extern lv_obj_t * WIFI_List_Button; // Button object for scanning WIFI

extern lv_obj_t *ui_WIFI_AP_MAC_List; // AP MAC address list object
void ui_WIFI_list_event_cb(lv_event_t * e); // Event callback for WIFI list
//////////////wifi


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// SCREEN: wifi_ui_screen
//void ui_Main_WIFI_screen_init(void); // Initialize the Main WIFI screen
void ui_Wifi_Screen_init(void); // Initialize the Main WIFI screen
extern lv_obj_t * ui_Main_WIFI; // Main object for Main WIFI screen
extern lv_obj_t * ui_WIFI; // WIFI panel object
extern lv_obj_t * ui_WIFI_STA; // WIFI Station object
extern lv_obj_t * ui_WIFI_SCAN_STA; // WIFI Scan Station object
void ui_event_WIFI_Button0(lv_event_t * e); // Event handler for Button0 on WIFI screen
extern lv_obj_t * ui_WIFI_Button0; // Button0 object on WIFI screen
extern lv_obj_t * ui_WIFI_Label0; // Label0 object on WIFI screen
void ui_event_WIFI_OPEN(lv_event_t * e); // Event handler for WIFI open action
extern lv_obj_t * ui_WIFI_OPEN; // Open WIFI object
extern lv_obj_t * ui_WIFI_STA_Label; // WIFI Station label object
extern lv_obj_t * ui_WIFI_List_Win; // WIFI List window object
extern lv_obj_t * ui_WIFI_Spinner; // Spinner object for scanning WIFI
extern lv_obj_t * ui_WIFI_Details_Win; // WIFI details window object
extern lv_obj_t * ui_WIFI_Name; // WIFI Name label object
extern lv_obj_t * ui_WIFI_Aurhmode; // Authentication mode label object
extern lv_obj_t * ui_WIFI_Pairwise; // Pairwise label object
extern lv_obj_t * ui_WIFI_Group; // Group label object
extern lv_obj_t * ui_WIFI_Channel; // Channel label object
extern lv_obj_t * ui_WIFI_IP; // IP address label object
void ui_event_WIFI_Connection_BUTTON(lv_event_t * e); // Event handler for WIFI connection button
extern lv_obj_t * ui_WIFI_Connection_BUTTON; // WIFI connection button object
extern lv_obj_t * ui_Connection; // Connection status label object
void ui_event_WIFI_INPUT_PWD(lv_event_t * e); // Event handler for WIFI password input
extern lv_obj_t * ui_WIFI_INPUT_PWD; // WIFI password input object
void ui_event_WIFI_EYE(lv_event_t * e); // Event handler for showing/hiding password
extern lv_obj_t * ui_WIFI_EYE; // Eye icon for password visibility
extern lv_obj_t * ui_WIFI_INPUT_KEYBOARD; // Keyboard object for password input
extern lv_obj_t * ui_WIFI_Wait_CONNECTION; // Waiting for connection label object
extern lv_obj_t * ui_WIFI_PWD_Error; // WIFI password error label object

extern lv_obj_t * ui_WIFI_AP; // WIFI AP object
extern lv_obj_t * ui_WIFI_OPEN_AP_; // Open AP object
void ui_event_WIFI_Button2(lv_event_t * e); // Event handler for Button2 on WIFI AP screen
extern lv_obj_t * ui_WIFI_Button2; // Button2 object on WIFI AP screen
extern lv_obj_t * ui_WIFI_Label2; // Label2 object on WIFI AP screen
void ui_event_WIFI_AP_OPEN(lv_event_t * e); // Event handler for opening WIFI AP
extern lv_obj_t * ui_WIFI_AP_OPEN; // Open AP object on WIFI AP screen
extern lv_obj_t * ui_WIFI_AP_INPUT_ERROR; // Error input object on WIFI AP screen
extern lv_obj_t * ui_WIFI_AP_Information; // AP Information object
void ui_event_WIFI_AP_NAME(lv_event_t * e); // Event handler for AP name input
extern lv_obj_t * ui_WIFI_AP_NAME; // AP name input object
void ui_event_WIFI_AP_Password(lv_event_t * e); // Event handler for AP password input
extern lv_obj_t * ui_WIFI_AP_Password; // AP password input object
void ui_event_WIFI_AP_EYE(lv_event_t * e); // Event handler for showing/hiding AP password
extern lv_obj_t * ui_WIFI_AP_EYE; // Eye icon for AP password visibility
void ui_event_WIFI_AP_Channel(lv_event_t * e); // Event handler for AP channel input
extern lv_obj_t * ui_WIFI_AP_Channel; // AP channel input object
extern lv_obj_t * ui_WIFI_AP_NAME_Label; // AP name label
extern lv_obj_t * ui_WIFI_AP_PWD_Label; // AP password label
extern lv_obj_t * ui_WIFI_AP_Channel_Label; // AP channel label
extern lv_obj_t * ui_WIFI_AP_MAC_ADDR; // AP MAC address label
extern lv_obj_t * ui_WIFI_AP_CON_NUM; // AP connection number label
extern lv_obj_t * ui_WIFI_AP_Keyboard; // AP keyboard object

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rat_hai_long_165x165_png);    // assets/rat hai long 165x165.png
LV_IMG_DECLARE(ui_img_hai_long_165x165_png);    // assets/hai long 165x165.png
LV_IMG_DECLARE(ui_img_binh_thuong_165x165_png);    // assets/binh thuong 165x165.png
LV_IMG_DECLARE(ui_img_that_vong_165x165_png);    // assets/that vong 165x165.png
LV_IMG_DECLARE(ui_img_rat_khong_hai_long_165x165_png);    // assets/rat khong hai long 165x165.png
LV_IMG_DECLARE(ui_img_27268529);    // assets/Argibank_logo.svg (2).png
LV_IMG_DECLARE(ui_img_167099737);    // assets/8212616 (1).png
LV_IMG_DECLARE(ui_img_star_grey_png);    // assets/star grey.png
LV_IMG_DECLARE(ui_img_1105461608);    // assets/turn back2 (2).png
LV_IMG_DECLARE(ui_img_1749747114);    // assets/right arrow  (1).png
LV_IMG_DECLARE(ui_img_656053819);    // assets/1946488 (1).png
LV_IMG_DECLARE(ui_img_608776254);    // assets/439328 (1) (1).png


LV_IMG_DECLARE(ui_img_wifi_1_png);    // Image for wifi level 1 from assets/wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // Image for wifi level 2 from assets/wifi_2.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // Image for wifi level 3 from assets/wifi_3.png
LV_IMG_DECLARE(ui_img_wifi_4_png);    // Image for wifi level 4 from assets/wifi_4.png
LV_IMG_DECLARE(ui_img_eye_png);    // Image for eye (visibility toggle) from assets/eye.png
LV_IMG_DECLARE(ui_img_ok_png);    // Image for OK button from assets/OK.png
LV_IMG_DECLARE(ui_img_log_on_png);
LV_IMG_DECLARE(wifi_1_100x100);
LV_IMG_DECLARE(wifi_1_20x20);
LV_IMG_DECLARE(wifi_2_20x20);
LV_IMG_DECLARE(wifi_3_20x20);
LV_IMG_DECLARE(wifi_4_20x20);
LV_IMG_DECLARE(ui_img_nowifi_50x50_png);
LV_IMG_DECLARE(ui_img_wifiicon2_50x50_png);
LV_IMG_DECLARE(ui_img_nowifi3_50x50_trans_png);    // assets/nowifi3 50x50 trans.png
LV_IMG_DECLARE(ui_img_wifi1_tran_png);    // assets/wifi1 tran.png
LV_IMG_DECLARE(ui_img_785059581);    // assets/wifi_2_100x100-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_1279478591);    // assets/wifi_3_100x100-removebg-preview (2).png
LV_IMG_DECLARE(ui_img_776640815);    // assets/wifi_4_100x100-removebg-preview.png
LV_IMG_DECLARE(ui_img_green_circle_2_70x70_png);    // assets/wifi_3_100x100-removebg-preview (2).png
LV_IMG_DECLARE(ui_img_red_circle_70x70_png);    // assets/wifi_4_100x100-removebg-preview.png
LV_IMG_DECLARE(ui_img_red_circle_20x20_png);    // assets/wifi_4_100x100-removebg-preview.png
LV_IMG_DECLARE(ui_img_turn_back2_png);


// FONTS
LV_FONT_DECLARE(ui_font_BOLD_VN20);
LV_FONT_DECLARE(ui_font_BOLD_VN25);
LV_FONT_DECLARE(ui_font_BOLD_VN30);
LV_FONT_DECLARE(ui_font_BOLD_VN35);
LV_FONT_DECLARE(ui_font_BOLDVN60);
LV_FONT_DECLARE(ui_font_BOLDVN80);
LV_FONT_DECLARE(ui_font_BOLDVN250);
LV_FONT_DECLARE(ui_font_BOLDVN250);
LV_FONT_DECLARE(lv_font_montserrat_24);
LV_FONT_DECLARE(lv_font_montserrat_20);
LV_FONT_DECLARE(ui_font_Chinese_Font);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
