// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "ui.h"
#include <stdio.h>
#include "wifi.h"




#include "nvs_flash.h"
#include "nvs.h"
#include <string.h>
#include "esp_log.h" // Thêm thư viện log

bool wifi_open=false;

//static const char *TAG = "RECONNECT";

// Hàm đọc thông tin Wi-Fi từ NVS
/*
esp_err_t read_wifi_credentials_from_nvs(char *ssid, size_t *ssid_len, char *password, size_t *password_len) {
    nvs_handle_t my_handle;
    esp_err_t err;

    err = nvs_open("wifi_cred", NVS_READONLY, &my_handle);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Lỗi khi mở NVS handle (%s)", esp_err_to_name(err));
        return err;
    }

    err = nvs_get_str(my_handle, "ssid", ssid, ssid_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Lỗi khi đọc SSID từ NVS (%s)", esp_err_to_name(err));
        nvs_close(my_handle);
        return err;
    }

    err = nvs_get_str(my_handle, "password", password, password_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Lỗi khi đọc mật khẩu từ NVS (%s)", esp_err_to_name(err));
        nvs_close(my_handle);
        return err;
    }

    nvs_close(my_handle);
    return ESP_OK;
}
*/
// Hàm mới để kết nối lại tới Wi-Fi đã lưu
/*
void reconnect_to_saved_wifi() {
    char ssid_from_nvs[32] = {0};
    char password_from_nvs[64] = {0};
    size_t ssid_len = sizeof(ssid_from_nvs);
    size_t password_len = sizeof(password_from_nvs);

    esp_err_t err = read_wifi_credentials_from_nvs(ssid_from_nvs, &ssid_len, password_from_nvs, &password_len);

    if (err == ESP_OK) {
        ESP_LOGI(TAG, "Tìm thấy thông tin Wi-Fi đã lưu. Đang tự động kết nối lại.");
        ESP_LOGI(TAG, "SSID: %s", ssid_from_nvs);
        
        // Gọi hàm khởi tạo kết nối Wi-Fi với thông tin đã đọc
        wifi_sta_init((uint8_t*)ssid_from_nvs, (uint8_t*)password_from_nvs, WIFI_AUTH_WPA2_PSK);
    } else {
        ESP_LOGI(TAG, "Không có thông tin Wi-Fi đã lưu. Không thể tự động kết nối lại.");
        // Bạn có thể thêm logic ở đây để chuyển sang chế độ cấu hình Wi-Fi nếu cần
    }
}

*/

// Event callback for opening the WiFi STA (station) connection
// This function opens a WiFi STA connection and modifies UI elements accordingly.
void WIFIOPEN(lv_event_t * e)
{   
    wifi_open=true;
    // Open WiFi in STA mode (station mode)
    wifi_open_sta();
    
    // Disable the "Open WiFi" and "Open WiFi AP" buttons
    _ui_state_modify(ui_WIFI_OPEN, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    _ui_state_modify(ui_WIFI_AP_OPEN, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    
    // Show the loading spinner while scanning for available networks
    _ui_flag_modify(ui_WIFI_Spinner, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE); 

    
    // Set the WiFi scan flag to true
    WIFI_SCAN_FLAG = true;


    ////////
    //////////
}

// Event callback for closing the WiFi STA connection
// This function closes the WiFi STA connection and updates the UI.
void WIFICLOSE(lv_event_t * e)
{   
    wifi_open=false;
    // Close the WiFi STA connection
    wifi_close_sta();
    
    // Clean the list of available WiFi networks
    lv_obj_clean(ui_WIFI_SCAN_List);
    
    // Show the WiFi details window (in case any details need to be shown)
    _ui_flag_modify(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}

// Event callback for establishing a WiFi connection
// This function connects to the WiFi using the entered password.
void WIFIConnection(lv_event_t * e)
{
    // Disable the "Open WiFi" button
    _ui_state_modify(ui_WIFI_OPEN, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    
    // Get the password from the password input field
    wifi_pwd = (uint8_t *)lv_textarea_get_text(ui_WIFI_INPUT_PWD);
    
    // Set the WiFi STA flag to true, indicating an active connection attempt
    WIFI_STA_FLAG = true;
}

// Event callback for opening a WiFi Access Point (AP)
// This function sets up the AP mode with the provided SSID, password, and channel.
void WIFIAPOPEN(lv_event_t * e)
{
    // Get the SSID, password, and channel from the respective input fields
    const char *ssid = lv_textarea_get_text(ui_WIFI_AP_NAME);
    const char *pwd = lv_textarea_get_text(ui_WIFI_AP_Password);
    const char *channel = lv_textarea_get_text(ui_WIFI_AP_Channel);
    
    // Check if all the required fields (SSID, password, and channel) are provided
    if (ssid != NULL && strlen(ssid) > 0 && 
        pwd != NULL && strlen(pwd) > 0 && 
        channel != NULL && strlen(channel) > 0) {
        
        // If all fields are filled, initialize and open the AP
        wifi_open_ap();
        wifi_ap_init((uint8_t *)ssid, (uint8_t *)pwd, atoi(channel));
        
        // Set the WiFi AP flag to true, indicating the AP is active
        WIFI_AP_FLAG = true;
        
        // Update the label to show the number of connections (initially 0)
        lv_label_set_text(ui_WIFI_AP_CON_NUM, "Connected: 0");

    } else {
        // If one or more fields are empty, handle the error case
        printf("One or more fields are empty: SSID, Password or Channel \r\n");
        
        // Uncheck the "Open WiFi AP" button and show an error message
        _ui_state_modify(ui_WIFI_AP_OPEN, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_WIFI_AP_INPUT_ERROR, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_STATE_REMOVE);
    }
}

// Event callback for closing the WiFi Access Point (AP)
// This function closes the AP and disables the WiFi AP flag.
void WIFIAPCLOSE(lv_event_t * e)
{
    // Set the WiFi AP flag to false, indicating the AP is closed
    WIFI_AP_FLAG = false;
    
    // Close the WiFi AP connection
    wifi_close_ap();
}

