// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_mqtt_client.h"
#include "mqtt_data.h"

#define MAX_DEVICES 20
#define MAX_NAME_LEN 32
#define MAX_ID_LEN   32

lv_obj_t * ui_Screen10 = NULL;
lv_obj_t* ui_DeviceList_Container=NULL;
lv_obj_t * ui_Image44 = NULL;

char tmp_id[18]={0};


extern device_info_t device_list[MAX_DEVICES];
extern int device_count;
extern esp_err_t load_device_list_from_nvs(void);

esp_err_t read_selected_device_id1(char *out_id, size_t out_len)
{
    if (out_id == NULL || out_len == 0) {
        return ESP_ERR_INVALID_ARG;
    }

    nvs_handle_t nvs_handle;
    esp_err_t err = nvs_open("SAVE_DEVICE_ID", NVS_READONLY, &nvs_handle);
    if (err != ESP_OK) {
        ESP_LOGE("READ_DEVICE_ID", "Can't open NVS: %s", esp_err_to_name(err));
        return err;
    }

    size_t required_size = out_len;
    err = nvs_get_str(nvs_handle, "device_id", out_id, &required_size);

    if (err == ESP_ERR_NVS_NOT_FOUND) {
        ESP_LOGW("READ_DEVICE_ID", "Key \"device_id\" khÃ´ng tá»“n táº¡i");
    }
    else if (err == ESP_ERR_NVS_INVALID_LENGTH) {
        ESP_LOGE("READ_DEVICE_ID", "Chuá»—i trong NVS dÃ i hÆ¡n buffer (%d > %d)", required_size, out_len);
    }
    else if (err == ESP_OK) {
        ESP_LOGI("READ_DEVICE_ID", "Read device_id: %s", out_id);
    }
    else {
        ESP_LOGE("READ_DEVICE_ID", "Error reading: %s", esp_err_to_name(err));
    }

    nvs_close(nvs_handle);
    return err;
}


void save_selected_device_id(const char *id)
{
    
    nvs_handle_t nvs_handle;
    esp_err_t err = nvs_open("SAVE_DEVICE_ID", NVS_READWRITE, &nvs_handle);
    if (err != ESP_OK) {
        ESP_LOGE("SAVE_DEVICE_ID", "Can't open NVS: %s", esp_err_to_name(err));
        return;
    }

    char temp[19];
    size_t required_size = sizeof(temp);


    err = nvs_get_str(nvs_handle, "device_id", temp, &required_size);
   
    if (err == ESP_ERR_NVS_INVALID_LENGTH) {
        ESP_LOGW("SAVE_DEVICE_ID", "device id is too long -> erasing");
        nvs_erase_key(nvs_handle, "device_id");
    }

    err = nvs_set_str(nvs_handle, "device_id", id);
    if (err == ESP_OK) {
        err = nvs_commit(nvs_handle);
        if (err == ESP_OK) {
            ESP_LOGI("SAVE_DEVICE_ID", "Saved number \"%s\" into key \"%s\"", id, "device_id");
        } else {
            ESP_LOGE("SAVE_DEVICE_ID", "Commit failed: %s", esp_err_to_name(err));
        }
    } else {
        ESP_LOGE("SAVE_DEVICE_ID", "Save failed (%s): %s", "device_id", esp_err_to_name(err));
    }

    nvs_close(nvs_handle);
}



static void device_button_event_handler(lv_event_t * e)
{
    lv_obj_t *btn = lv_event_get_target(e);
    int index = (int)lv_event_get_user_data(e);

    if (index >= 0 && index < device_count) {
        ESP_LOGI("LVGL", "Clicked device: %s - %s",
                 device_list[index].name,
                 device_list[index].device_id);
       // strncpy(selected_device_id,device_list[index].device_id,sizeof(selected_device_id));
       // save_selected_device_id(selected_device_id);
       save_selected_device_id(device_list[index].device_id);
       // ESP_LOGI("SELECTED_DEVICE_ID","%s",selected_device_id);
         ESP_LOGI("SELECTED_DEVICE_ID","%s",device_list[index].device_id);
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen7_screen_init);
       ui_Screen10_screen_init();//

   
    }
}

void ui_show_device_list(lv_obj_t *parent)
{
    lv_obj_clean(parent);
    lv_obj_set_style_border_color(parent, lv_color_white(), 0);


    lv_obj_set_flex_flow(parent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(parent, 15, 0);     
    lv_obj_set_style_pad_all(parent, 10, 0);     
    lv_obj_set_scroll_dir(parent, LV_DIR_VER);    

    for (int i = 0; i < device_count && i < MAX_DEVICES; i++) {
        lv_obj_t *btn = lv_btn_create(parent);
        lv_obj_set_size(btn, LV_PCT(90), 70);     
        lv_obj_set_style_radius(btn, 15, 0);    
        lv_obj_set_style_bg_color(btn, lv_color_hex(0x337ab7), 0);  
        lv_obj_set_style_bg_opa(btn, LV_OPA_80, 0);
        lv_obj_set_style_border_width(btn, 0, 0);
        lv_obj_set_style_border_color(btn, lv_color_white(), 0);


        lv_obj_t *label = lv_label_create(btn);
        lv_label_set_text(label, device_list[i].name);
        lv_obj_set_style_text_font(label, &lv_font_montserrat_20, 0); 
         if (read_selected_device_id1(tmp_id,sizeof(tmp_id))==ESP_OK){
            if (strcmp(tmp_id,device_list[i].device_id)==0){
                lv_obj_set_style_text_color(label, lv_color_black(), 0);
            }
        }
        else {
        lv_obj_set_style_text_color(label, lv_color_white(), 0);
        }
        //lv_obj_set_style_text_color(label, lv_color_white(), 0);
        lv_obj_center(label);

        //device_index[i] = i;
        lv_obj_add_event_cb(btn, device_button_event_handler, LV_EVENT_CLICKED, (void*)i);
    }

    ESP_LOGI("LVGL", "Displayed %d devices", device_count);
}


void ui_event_Image44(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen9_screen_init);
    }
}


void ui_Screen10_screen_init(void)
{   
    ui_Screen10 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen10, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image44 = lv_img_create(ui_Screen10);
    lv_img_set_src(ui_Image44, &ui_img_turn_back2_png);
    lv_obj_set_width(ui_Image44, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Image44, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Image44, -447);
    lv_obj_set_y(ui_Image44, 247);
    lv_obj_set_align(ui_Image44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image44, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_add_event_cb(ui_Image44, ui_event_Image44, LV_EVENT_ALL, NULL);

    ui_DeviceList_Container = lv_obj_create(ui_Screen10);
    lv_obj_set_size(ui_DeviceList_Container, 240, 280);
    lv_obj_center(ui_DeviceList_Container);

    esp_err_t err = load_device_list_from_nvs();
    if (err == ESP_OK && device_count > 0) {
        ESP_LOGI("UI", "Loaded %d devices, showing...", device_count);
        ui_show_device_list(ui_DeviceList_Container);
    } else {
        ESP_LOGW("UI", "No device found in NVS or error");
        lv_obj_t *label = lv_label_create(ui_DeviceList_Container);
        lv_label_set_text(label, "No saved device");
        lv_obj_center(label);
    }
}


void ui_Screen10_screen_destroy(void)
{
    if(ui_Screen10) lv_obj_del(ui_Screen10);

    // NULL screen variables
    ui_Screen10 = NULL;

}
