// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Image40 = NULL;


static int click_count = 0;
static uint32_t last_click_time = 0;

extern int cnt;
static int change=0;
// event funtions

// build funtions

static void area_click_event_cb(lv_event_t *e) {
        uint32_t current_time = lv_tick_get();

    if ((current_time - last_click_time) < 5000) {
        click_count++;
    } else {
        click_count = 1;
        last_click_time = current_time;
    }

    if (click_count >= 7) {
        click_count = 0;
        //change=1;//
        _ui_screen_change(&ui_Main_WIFI, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Wifi_Screen_init);


        /////////
 if (cnt!=0){

    // Bắt đầu scan Wi-Fi (non-blocking)
    //wifi_scan();
    _ui_state_modify(ui_WIFI_OPEN, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);//
    lv_obj_clean(ui_WIFI_SCAN_List);
    _ui_flag_modify(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
     _ui_flag_modify(ui_WIFI_Spinner, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE); //
     
    WIFI_SCAN_FLAG=true;
}

    }
    
    last_click_time = current_time;
}

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "1002");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xD74949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_BOLDVN250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel16, 1028);
    lv_obj_set_height(ui_Panel16, 130);
    lv_obj_set_x(ui_Panel16, 0);
    lv_obj_set_y(ui_Panel16, -237);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xA59898), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image40 = lv_img_create(ui_Panel16);
    lv_img_set_src(ui_Image40, &ui_img_27268529);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_Image40, -5);
    lv_obj_set_y(ui_Image40, 0);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags



    lv_obj_t * area = lv_obj_create(ui_Screen7);
    lv_obj_set_size(area, 100, 100);
    //lv_obj_set_style_bg_color(area, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(area, LV_OPA_TRANSP, LV_PART_MAIN);   // Ẩn nền
    lv_obj_set_style_border_opa(area, LV_OPA_TRANSP, LV_PART_MAIN); // Ẩn viền
    lv_obj_set_style_outline_opa(area, LV_OPA_TRANSP, LV_PART_MAIN); // Ẩn viền ngoài
    lv_obj_align(area, LV_ALIGN_TOP_LEFT, 0, 0);

    lv_obj_add_event_cb(area,area_click_event_cb,LV_EVENT_CLICKED,NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Label26 = NULL;
    ui_Panel16 = NULL;
    ui_Image40 = NULL;

}
