// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN9_H
#define UI_SCREEN9_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen9
extern void ui_Screen9_screen_init(void);
extern void ui_Screen9_screen_destroy(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label27;
extern void ui_event_Panel18(lv_event_t * e);
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label29;
extern void ui_event_Image42(lv_event_t * e);
extern lv_obj_t * ui_Image42;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

