// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "nvs_flash.h"
#include "lvgl_port.h"

lv_obj_t * ui_Screen9 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Image42 = NULL;

extern void save_status(const char *status);

esp_err_t delete_current_number_from_nvs(void) {
    nvs_handle_t my_handle;
    esp_err_t err = nvs_open("number_cred", NVS_READWRITE, &my_handle);
    if (err != ESP_OK) return err;

    // Xóa key
    err = nvs_erase_key(my_handle, "current_number");
    if (err != ESP_OK) {
        nvs_close(my_handle);
        return err;  // Có thể là ESP_ERR_NVS_NOT_FOUND
    }

    // Commit để lưu thay đổi vào flash
    err = nvs_commit(my_handle);
    nvs_close(my_handle);

    return err;
}

// event funtions
void ui_event_Panel17(lv_event_t * e)

{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main_WIFI, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Wifi_Screen_init);
    }
}
void ui_event_Panel18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen10, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Screen10_screen_init);
    }
}

void ui_event_Panel19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
         if (lvgl_port_lock(-1)) {
                    lv_label_set_text(ui_Label26, "0000");
                    lv_obj_set_style_text_font(ui_Label26, &ui_font_BOLDVN250, LV_PART_MAIN | LV_STATE_DEFAULT);
                    lvgl_port_unlock();
                }
             delete_current_number_from_nvs();
             save_status("NO");
             
            _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Screen7_screen_init);

    }
}

void ui_event_Image42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen7_screen_init);
    }
}

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_Screen9);
    lv_obj_set_width(ui_Panel17, 219);
    lv_obj_set_height(ui_Panel17, 50);
    lv_obj_set_x(ui_Panel17, -24);
    lv_obj_set_y(ui_Panel17, -177);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x2EBE2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, -2);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "WIFI");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Panel18 = lv_obj_create(ui_Screen9);
    lv_obj_set_width(ui_Panel18, 219);
    lv_obj_set_height(ui_Panel18, 50);
    lv_obj_set_x(ui_Panel18, -18);
    lv_obj_set_y(ui_Panel18, -41);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x2EBE2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "KEYPAD");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    
    ui_Panel19 = lv_obj_create(ui_Screen9);
    lv_obj_set_width(ui_Panel19, 219);
    lv_obj_set_height(ui_Panel19, 50);
    lv_obj_set_x(ui_Panel19, -16);
    lv_obj_set_y(ui_Panel19, 93);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x2EBE2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "RESET");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    ui_Image42 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image42, &ui_img_turn_back2_png);
    lv_obj_set_width(ui_Image42, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_Image42, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Image42, -447);
    lv_obj_set_y(ui_Image42, 247);
    lv_obj_set_align(ui_Image42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Panel17, ui_event_Panel17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel18, ui_event_Panel18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel19, ui_event_Panel19, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Image42, ui_event_Image42, LV_EVENT_ALL, NULL);

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;
    ui_Panel17 = NULL;
    ui_Label27 = NULL;
    ui_Panel18 = NULL;
    ui_Label28 = NULL;
    ui_Panel19 = NULL;
    ui_Label29 = NULL;
    ui_Image42 = NULL;

}
