// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "lvgl.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Button12 = NULL;

//static lv_obj_t *area=NULL;


static int click_count = 0;
static uint32_t last_click_time = 0;

extern int cnt;
static int change=0;

// event funtions

// build funtions


static void area_click_event_cb(lv_event_t *e) {
        uint32_t current_time = lv_tick_get();

    if ((current_time - last_click_time) < 5000) {
        click_count++;
    } else {
        click_count = 1;
        last_click_time = current_time;
    }

    if (click_count >= 7) {
        click_count = 0;
        change=1;//
        _ui_screen_change(&ui_Main_WIFI, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Wifi_Screen_init);


        /////////
        if (cnt!=0){

    // Bắt đầu scan Wi-Fi (non-blocking)
    //wifi_scan();
    _ui_state_modify(ui_WIFI_OPEN, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);//
    lv_obj_clean(ui_WIFI_SCAN_List);
    _ui_flag_modify(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
     _ui_flag_modify(ui_WIFI_Spinner, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE); //
     
    WIFI_SCAN_FLAG=true;
}

    }
    
    last_click_time = current_time;
}


void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Panel14 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel14, 464);
    lv_obj_set_height(ui_Panel14, 130);
    lv_obj_set_x(ui_Panel14, -22);
    lv_obj_set_y(ui_Panel14, -110);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 16);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "123\n");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_BOLD_VN35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button12, 100);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -16);
    lv_obj_set_y(ui_Button12, 102);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);


    lv_obj_t * area = lv_obj_create(ui_Screen6);
    lv_obj_set_size(area, 100, 100);
    lv_obj_set_style_bg_color(area, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_align(area, LV_ALIGN_TOP_LEFT, 0, 0);

    lv_obj_add_event_cb(area,area_click_event_cb,LV_EVENT_CLICKED,NULL);


}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Panel14 = NULL;
    ui_Label23 = NULL;
    ui_Button12 = NULL;

}